name: build-sdk
run-name: Build SDK
on: [push]
jobs:
  build-sdk-13_r18:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - run: bash sdk-13.0.0_r18/gh-actions-build.sh
      - run: df -h
      - run: sudo mkdir -p /mnt/build-sdk-13_r18
      - run: sudo chmod a+rwx /mnt/build-sdk-13_r18
      - working-directory: /mnt/build-sdk-13_r18
        run: bash ${{ github.workspace }}/dependencies.sh
      - working-directory: /mnt/build-sdk-13_r18
        run: bash ${{ github.workspace }}/download.sh
      - working-directory: /mnt/build-sdk-13_r18
        run: bash ${{ github.workspace }}/build.sh
